### ISSUE TITLE
Videos on docs.devwithlando.io.

### ISSUE THREAD

**Issue by serundeputy** [thinktandem/tandem#100]
## What is to be done?

We switched docs.devwithlando.io site to Vuepress and lost our video embeds.

- [ ] Figure out youtube embedding in Vuepress (find and configure a plugin)
- [ ] Decide what vids and where
  - [ ] Embed them into the vuepress site

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

More video content. Once we have the infra and the money spin up more youtube/lando content and integrate with the docs and promotional materials.

**Comment by pirog** [comment]
@serundeputy closing this in favor of #107
