### ISSUE TITLE
Develop a checklist of criteria for responding to RFPs

### ISSUE THREAD

**Issue by labboy0276** [thinktandem/tandem#102]
## What is to be done?

As @reynoldsalec and myself has been discussing, we need to come up with criteria for responding to RFPs.  We have had 0% success on all RFPs we have responded to.  This was mainly due to responding to clients RFPs we did not know or have a good foot in the door.  We do want to occasionally respond, so the criteria must be set.

## Task checklist

- [ ] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [ ] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [ ] I've added a story point estimation. **This should never exceed 3!!!**
- [ ] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [ ] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

- [ ] Develop minimum acceptance levels for responding to RFPs.
