### ISSUE TITLE
Tandem Availability

### ISSUE THREAD

**Issue by reynoldsalec** [thinktandem/tandem#106]
## What is to be done?

We need to document when we are available to our clients (and under what terms). This will allow our project managers to confidently communicate our boundaries and remove room for misunderstandings with clients.

**Availability + Support Prioritization**

- Team members are available 9am - 5pm in their timezone (typically EST) -> this relates to #
- Slack is to be used for urgent real-time communication. Default response is best-effort; typically urgent matters can be responded to within a couple hours during your team's working hours (should emphasize this window).
- Clients who have payed for dedicated time contracts (typically recurring support agreements or multi-month projects) can expect prioritized support/regular work hours compared to clients who have one-time contracts that access Tandem services when available.
- Emergency support can be made available from 9am - 9pm EST at an elevated hourly rate; this must be negotiated into your contract.
- Weekend and off-hours support is always best effort.

**Communication Methods**

- Task-related comments should be added to the issue tracker. Urgent issues should be added to the issue tracker, but please notify the team about them immediately on Slack.
- Urgent issues and conversations should take place on Slack. Often even if you're working primarily with one Tandem developer, other Tandem team members are watching your Slack channel and can jump in if your main developer is unavailable.
- Phone support is only provided after special contract negotiation. If you're given a Tandem team member's phone number without purchasing emergency support, realize that they will only be available during their working hours. Slack is strongly preferred to texting or calling. Voice calling is available via Slack.

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

I haven't created issues for these but we may want to follow-up with these topics:

- [ ] Contract modifications that mirror these basic guidelines.
- [ ] Discuss emergency + urgent support guidelines. How do we sell these? Plans that relate to different response times/availability? What plan options do I have as a client?
- [ ] Automated messaging to reinforce our response times for different plans/clients?
- [ ] Best way to funnel conversations to the right people on the right channels, but keep noise down?
- [ ] Google Voice or other "company phone" for calling out to clients (and possibly receiving calls)?

**Comment by pirog** [comment]
@reynoldsalec we've got a task to spin up a remote working environment section for the handbook over at #113, maybe a bunch of this stuff (eg the part around employee expectations) could fit in there? The rest probably should go into some sort of PM guide around client communications and expectations.

Some additional notes i had made during our convo were

1. Phone use should be discouraged as much as possible. If phone numbers are to be used lets find a way we can give out Tandem numbesr via google voice or some other service like http://yodel.io/
2. Encourage stuff to end up in slack as much as possible
3. Eventually we need to figure out better ways to notify the right people to get eyes on things, presumably with some slack alert system thing that _sounds_ and _feels_ similar to what we want to do over at #38 

@reynoldsalec how do you want to proceed here? Can you spin up a few tasks or discussions that make sense to you so we can get the ball rolling?
