### ISSUE TITLE
Add videos back into docs.devwithlando.io

### ISSUE THREAD

**Issue by serundeputy** [thinktandem/tandem#107]
## What is to be done?

When we moved the lando docs to vuepress we lost the videos.  This task is to add them back.  Here are the steps:

* Get the embed code for the video from youtube
* add a `div` to the markdown file in question with class `vids` and paste in the embed code; here is an example with the `docs/basics/intallation.md` file:

```html
Prefer video?
<div class="vids">
<iframe width="560" height="315" src="https://www.youtube.com/embed/W8qIutOAe-0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
```
* add and commit the code to a `107/installVid` branch where the branch reflects the video/doc page you are working on
* push up the code to `lando/lando` then file a PR

## Task checklist

- [ ] `installation.md`
  * PR: https://github.com/lando/lando/pull/1773

- [ ] Lando + PhpStorm + Xdebug
- [ ] Lando + Mailhog
- [ ] Lando + Drupal 8 Core Contributions
- [ ] Lando + Drupal 7
- [ ] Lando + Databases
  * this was on the `db-import` and `db-export` docs
- [ ] Lando + Laravel
- [ ] Lando + WordPress
- [ ] Lando + Pantheon + Drupal 8
- [ ] Lando + Drupal 8
- [ ] Lando + Backdrop

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

This is a one off task to add the videos back into the documentation.

**Comment by serundeputy** [comment]
Installation documentation w/ vid.
PR: https://github.com/lando/lando/pull/1773

**Comment by serundeputy** [comment]
ressponsive vids
https://github.com/lando/lando/pull/1773#issuecomment-528313811
