### ISSUE TITLE
Quarterly Review & Checking Reference Docs Review

### ISSUE THREAD

**Issue by labboy0276** [thinktandem/tandem#111]
## What is to be done?

This is a continuation of https://github.com/thinktandem/tandem/issues/77.  @reynoldsalec Will need to review the following docs to make sure they are up to snuff:

- [ ] https://docs.thinktandem.io/guides/quarterly-review.html
- [ ] https://docs.thinktandem.io/guides/reference-check.html

@reynoldsalec has the most experience with these items and can adjust the texts if need be.

## Task checklist

- [ ] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [ ] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [ ] I've added a story point estimation. **This should never exceed 3!!!**
- [ ] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [ ] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

@reynoldsalec to spin up new issues if there are subsequent tasks we should add to improve from here.
