### ISSUE TITLE
[lando-tandem plugin] Stub out lando new-project command

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#112]
## What is to be done?

Using the loose spec over here 
https://github.com/thinktandem/lando-tandem#new-project

Let's stub out a basic `lando new-project` command. For now we dont need to worry about connecting and authenticating with the Tandem Hub, let's just make placeholder functions to simulate interacting with it that return the data we need. 

To kick this off lets

1. Have `lando new-project` do authentication similar to the pantheon integration eg token based auth that is saved locally. For now lets just authenticate against a list of all our emails.
2. Product a list of start states. Again, these can be hardcoded for now until Tandem Hub is fully operational @labboy0276 can likely give you the relevant metadata
3. Ask for a name of the project
4. Clone the project down and modify/create a lando file with the correct name

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

The below all need tickets eventually

- [ ] Automatic GitHub new repo creation
- [ ] Automatic platform.sh new site creation
- [ ] Automatic platform.sh GitHub integration setup
- [ ] Automatic platform.sh automatic backups
- [ ] Some sort of validation step to make sure ^ worked, and roll back if didnt
- [ ] Make sure all our start states are setup for easy usage with this system eg have working platform.sh config, lando config, travis config, etc.
