### ISSUE TITLE
What is our policy around security updates?

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#114]
## What is to be done?

This was motivated by the discussion over at
https://github.com/thinktandem/tandem/issues/68

We need to define a policy around security updates. Specifically we need to understand what Tandem is expected to do for all or specific subsets of our clients. For example

> Tandem actively monitors for _major_ drupal, php, node, etc, security updates for your sites and applies fixes for them within 24 hours if possible. 

This policy should likely end up in our docs and possibly marketing materials eg our website, sales campagains etc.

We may also want to suggest some guidelines around tech implementation eg prefer a GitHub dependabot-ish solution first before an in house one

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

- [ ] Communicate this policy to the team because it will likely inform our automation efforts. 
- [ ] Spin up additional tasks so we can start automating this policy
