### ISSUE TITLE
Document our current security update process

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#115]
## What is to be done?

This was motivated by the discussion over at
https://github.com/thinktandem/tandem/issues/68

We need to define our current process for doing security updates. Let's create a guide over at https://docs.thinktandem.io/guides/ that answers the question of "how does Tandem manage security updates?"

Once we've done that and defined an actual policy over in #114 we can start to work on the over phases outlined by @mikemilano in #68 

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

- [ ] Communicate the process to the team
- [ ] Work with the people in #114 to spin up a new task to start automating this process
