### ISSUE TITLE
D7 End of Life Campaign

### ISSUE THREAD

**Issue by reynoldsalec** [thinktandem/tandem#164]
## What is to be done?

Create a sales campaign highlighting D7's EoL date in 2022.

- https://ahrefs.com/keywords-explorer/google/us/overview?keyword=drupal%207%20end%20of%20life

## Task checklist

- [x] Create blog post about D7 EoL and your options.
- [x] Create email copy
- [x] Target list of D7 site owners
- [ ] Send campaign.

**Comment by reynoldsalec** [comment]
Published Blog Article: https://thinktandem.io/blog/2020/06/30/drupal-7-end-of-life-and-your-options/

Campaign Emails: https://docs.google.com/document/d/1XbXCg6ETFsEc0vl9y9mTg-u9oj3g9wX2nkhyNs3mZcU/edit#
