### ISSUE TITLE
META: Dedicate time to learn AHREFS, our main SEO tool

### ISSUE THREAD

**Issue by labboy0276** [thinktandem/tandem#17]
Make sure you have read about the [different kinds of tickets](https://tandem-docs.lndo.site/guides/improve-tandem.html#suggesting-a-change) and then complete the following questions

1. Describe the problem and how you think it most impacts [Tandem's goals/mission/values](https://docs.thinktandem.io/manifesto/)

Currently we have this tool https://ahrefs.com/ for our SEO diagnosis and tracking.  It is a very large and complex tool that we only have a surface level to rudimentary understanding of how to use it.  We are losing out on opportunities to help existing clients via fully understanding their SEO needs and issues.  Case in point, poets.  When the stuff hit the fan, we should of been able to turn to this tool and utilized its potential better.  Instead we outsourced it (which is fine) but we can do better.

2. Briefly describe the "fastest" thing we could do to begin to make things right.

They have an academy with about 10 hours of videos.  We should spend maybe every Friday going through them until it is done:  https://ahrefs.com/academy

Ahrefs also has a YouTube channel as well: https://www.youtube.com/channel/UCWquNQV8Y0_defMKnGKrFOQ

Another general guide, that provides a decent overview: https://www.shivarweb.com/6608/ahrefs-guide/

3. Briefly describe a "better" and more automated/tied in solution and how that would be better than the fastest.

Currently none, but they do have an API we can explore once we get better understanding the main tool: https://ahrefs.com/api  We could possibly incorporate this until all our projects.

4. Provide a few sentences about how you see this solution impacting various parts of the business

#### Operations

Ability to properly diagnose problems in projects and provide better service for our clients.

#### Marketing

We could write blog posts about diagnosing problems and how to fix them.  This adds to our street cred. 

#### Sales

We can sell more SEO packages.  If we figure out their API, we could automate that into our sales process to diagnose potential clients.  

#### Feels and Morale

Remove the feeling of hopelessness and confusion when a client takes a digger in Google rankings.  

5. Provide a _best estimate_ about a few things. Use the `better` solution to compute your estimate.

Rank things on a modified-fibonacci scale between 1-40 eg (1, 2, 3, 5, 8, 13, 21, 40).

```yaml
# How urgent is this?
Priority: 13

# How well does the proposed solution align with our values
Value Alignment: 21

# Story points we think this will take
# NOTE: do not set the actual story points on the ticket itself, we will use the
# points on subsequent action items
Effort: 13

# Value to various parts of the business
Operational Efficiency: 21
Marketing: 2
Sales: 13
Feels and Morale: 5
```

6. Add your entry to this spreadsheet with the above data.

@TODO: let's hold off on making this until we lock down the above a bit

7. How can we best distribute solution so it's in baked into our processes and not lost?

We need to develop a client on boarding process (probably another proposal / action item) and generate a report.  We could also incorporate this into our Audits.  This way we can identify pain points with the site (including SEO pain points) and return that to the client which could equate to more business.  

8. Generate a rough list of action items based on the above, eventually these should become action items

- [ ] Go through the courses on the Academy and watch an relevant videos
- [ ] Identify areas on Ahrefs that we can easily use to diagnose potential problems and areas of growth for our clients
- [ ] See if those areas above are in the API, if so automate it.
- [ ] Tie this process into on boarding, audits, and run against existing clients
- [ ] Write a blog post about it
- [ ] Develop another sales product around this

9. Does anything above require discussion or feedback before this proposal is ready for primetime?

- [ ] Is everyone going to go through this process or just the willing?

10. Make sure you complete the following checklist

I am not sure what to put here but I would say this affects operations the most and sales second

**Comment by pirog** [comment]
@labboy0276 for the sake of standardization im going to close this out and suggest you RESUBMIT as either a chain of tasks (if you've got a clear picture on what needs to happen) or as a "discussion" if you've like to get some more feedback

**Comment by pirog** [comment]
@labboy0276 fake out!

turns out it makes more sense to change this to a "note" and keep it open. You will need to put it through the new templates and then close it.
