### ISSUE TITLE
Define and clarify the "Keeper of the Faith" role and who should have said role

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#24]
## What is to be done?

We need to specify a "Keeper of the Faith" role and its responsibilities over at https://docs.thinktandem.io/manifesto/roles.html and then specify who occupies that role over at https://docs.thinktandem.io/manifesto/org.html.

This role should generally be responsible for managing the [company improvement process](https://docs.thinktandem.io/guides/improve-tandem.html) but could also do more things like ensuring the manifesto and its values are adhered to. 

The task is to flesh those things out on a high level eg it should be specific on responsibilities but probably not their implementation details. For example it should say things like "they are responsible for managing the board to accomplish x" but it might not say exactly _how_ that is to be done. 

_Some_ specific responsibilities i think would be good

1. Handle "orchestration" of issues. Our task/discussion framework is powerful but it needs a guide to make sure discussions end up as tasks, that tasks are chained together appropriately and that different task chains have context of other related chains
2. Function as a "project manager" for the "product that is tandem", this requires fleshing out the PM role better
3. Make sure tasks/discussions stay on target, have clearly defined purposes that solve biz problems

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task

## Next task(s)

- [ ] Review [company improvement docs](https://docs.thinktandem.io/guides/improve-tandem.html) https://github.com/thinktandem/tandem/issues/25
- [ ] Discuss issue management of this repo https://github.com/thinktandem/tandem/issues/26

**Comment by pirog** [comment]
@dustinleblanc i'm happy to do a first pass on this and then we can review/edit together. That way you can focus on stuff with MM first.

**Comment by pirog** [comment]
note for @pirog 

> living our values: make it a responsibility of owners/keepers of the faith impute fun in the docs
