### ISSUE TITLE
Keepers of the Faith should review the current company improvement docs

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#25]
## What is to be done?

Once the "Keeper of the Faith" role has been clarified in #24 said Keeper(s) of the Faith should review the [tandem improvement docs](https://docs.thinktandem.io/guides/improve-tandem.html) and suggest changes to make them more clear, simple and consistent. For example the terms _task_, _ticket_, _issue_, etc seem to be used interchangeably and we should just pick one. 

This may also imply a new task/discussion to _define_ these terms better in a glossary or other mechanism. 

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [ ] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task

## Next task(s)

We need a next ticket here but presumably it would be a task with a checklist of changes to make based on the review here

**Comment by pirog** [comment]
@dustinleblanc since the process is still fluid i think we should tackle this all the way at the end of Q3 when things have hopefully settled down. eg the task will basically be to update the docs to reflect whatever the "facts on the ground" are at that time.

**Comment by dustinleblanc** [comment]
Sounds good, we've got enough in the trenches work to take care of for now
