### ISSUE TITLE
Write out Tandems goals/roadmap in the manifesto docs

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#31]
## What is to be done?

Right now we have two contentless sections for "Goals" and "Roadmap" in the manifesto docs
https://tandem-docs.lndo.site/manifesto/

We probably should consolidate them into a single section and list high level goals and roadmap things on a regular (quarterly, yearly? basis)

This is a basically a placeholder task for @pirog and @reynoldsalec 

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [ ] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task

## Next steps(s)

Paste in a link to any tasks or discussions that should be done after this one is merged. You should _always_ try to find a "next thing" (or more) that can be done to continue the chain of progress.

> Example:
> - [ ] Description of a next ticket #link-to-that-ticket
> - [ ] Description of another ticket if applicable #link-to-that-ticket
> - [ ] Description of another ticket if applicable #link-to-that-ticket
> - [ ] ...
> - [ ] Description of Nth ticket if applicable #link-to-that-ticket
