### ISSUE TITLE
Complete the "history" section of our manfiesto

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#32]
## What is to be done?

We already discuss where we came from wrt this process in our horoscope history docs
https://tandem-docs.lndo.site/manifesto/horoscope.html

It would be great to add additional sections to our history. Specifically it might be nice to talk about

1. EBD -> Kalamuna -> Tandem
2. Kalabox -> Lando

This is a basically a placeholder task for @pirog and @reynoldsalec

## Task checklist

- [ ] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [ ] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [ ] I've added a story point estimation. **This should never exceed 3!!!**
- [ ] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task

## Next steps(s)

Paste in a link to any tasks or discussions that should be done after this one is merged. You should _always_ try to find a "next thing" (or more) that can be done to continue the chain of progress.

> Example:
> - [ ] Description of a next ticket #link-to-that-ticket
> - [ ] Description of another ticket if applicable #link-to-that-ticket
> - [ ] Description of another ticket if applicable #link-to-that-ticket
> - [ ] ...
> - [ ] Description of Nth ticket if applicable #link-to-that-ticket
