### ISSUE TITLE
List out the roles that tandem has

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#33]
## What is to be done?

We want to fill out the manifesto with roles
https://docs.thinktandem.io/manifesto/roles.html

This should probably be broken up into the same vuepress format as our other doc sections
eg https://github.com/thinktandem/tandem/blob/master/docs/.vuepress/config.js#L34

This is a basically a placeholder task for @pirog and @reynoldsalec. It should only be to LIST the roles we have. We can define their responsibilities in a subsequent ticket.

## Task checklist

- [ ] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [ ] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [ ] I've added a story point estimation. **This should never exceed 3!!!**
- [ ] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task

## Next steps(s)

We need to:

- [ ] Spin up a follow up ticket to clarify each roles responsibilities
- [ ] Spin up a follow up task after that to sketch out a "org/depth chart" eg to list which people do a given role and who their backups are
