### ISSUE TITLE
Enumerate "cardinal sins"

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#34]
## What is to be done?

In an open org like tandem its sometimes easier to enumerate the things NOT to do versus the things to do. Let's add a section to our manifesto for these so-called "cardinal sins"

Some initial ideas for those things are

  * duplicating work
  * breaking flow
  * not doing business building stuff eg this process
  * not doing billable targets

## Task checklist

- [ ] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [ ] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [ ] I've added a story point estimation. **This should never exceed 3!!!**
- [ ] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task

## Next steps(s)

Paste in a link to any tasks or discussions that should be done after this one is merged. You should _always_ try to find a "next thing" (or more) that can be done to continue the chain of progress.

> Example:
> - [ ] Description of a next ticket #link-to-that-ticket
> - [ ] Description of another ticket if applicable #link-to-that-ticket
> - [ ] Description of another ticket if applicable #link-to-that-ticket
> - [ ] ...
> - [ ] Description of Nth ticket if applicable #link-to-that-ticket
