### ISSUE TITLE
Audit relevant guides things from our old docs

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#35]
## What is to be done?

We have a bunch of older guide and handbook materials over at https://docs.v1.thinktandem.io/ (u: tandem, p: tandem). We need to move those over to the new docs as appropriate. 

We probably also want to make sure they use the same vuepress categorie sidebar format as other sections. 

This is basically a placeholder task for @pirog and/or @reynoldsalec.

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task

## Next steps(s)

After this is done we need a bunch of tasks or discussions to review and update the ported materials

- [ ] https://github.com/thinktandem/tandem/issues/60

**Comment by pirog** [comment]
@serundeputy i think it might be good for one of us to do an inventory of things first so we can see how things should map over. 

There is already this list of legacy guides that might serve as a good starting point:
https://docs.thinktandem.io/guides/#legacy-guides

I'm probably going to focus on other tickets first so if you could do a first pass on that inventory and mapping and then we can review together that would be great. We also need to queue up a next ticket for this... it might make sense for that ticket to be going through the docs we move over and making sure they are still applicable, spawning off cards with feedback as we go. What do you think?

**Comment by serundeputy** [comment]
Here is a outline to fill in our map from legacy guides:

Map Docs from Eld docs to New Docs Location
===========================================

categories
--------------

  * Dev Life
  * PM Life
  * DevOps Life
  * CompanyOps Life

docs
------

* Process Workflow
  * https://docs.v1.thinktandem.io/collab/process-workflow.html
  * NEW_DOCS_LOCATION
* Accesibility checklist / audit
  * https://docs.v1.thinktandem.io/discovery/accessibility-checklist.html
  * NEW_DOCS_LOCATION
* Writing code
  * https://docs.v1.thinktandem.io/coding/guidelines.html
  * NEW_DOCS_LOCATION
* QAing code
  * https://docs.v1.thinktandem.io/coding/qa.html
  * NEW_DOCS_LOCATION
* Selecting the right tool for the right job?
  * https://docs.v1.thinktandem.io/coding/common-tools.html
  * NEW_DOCS_LOCATION
  * @todo: change this to be our "tech inventory" eg tools and solutions we use for specific things, eg
    * lando for local
  * NEW_DOCS_LOCATION
    * vue for js frontend
    * vuepress for docs
  * NEW_DOCS_LOCATION
    * minimus for d8 start states
* Spinning up a new project
  * NEW_DOCS_LOCATION
  * https://docs.v1.thinktandem.io/coding/devops.html
  * @todo: this should also include
  * NEW_DOCS_LOCATION
    * Write out README.md
    * GitHub issue templates
  * NEW_DOCS_LOCATION
    * Write Architecture Plan
    * other readmes as necessary per project
  * NEW_DOCS_LOCATION
* Managing projects
  * https://docs.v1.thinktandem.io/project-management/project-lifecycle.html
  * NEW_DOCS_LOCATION
  * @todo: guessing we want to break this up into multiple guides
    * client qualification
  * NEW_DOCS_LOCATION
    * discovery/requirements gathering
    * dev design handoff
  * NEW_DOCS_LOCATION
    * project estimation
    * sprint planning
  * NEW_DOCS_LOCATION
    * etc
* Sales
  * NEW_DOCS_LOCATION
  * https://docs.v1.thinktandem.io/marketing/marketing-channels.html
* Identifying prospects
  * NEW_DOCS_LOCATION
  * https://docs.v1.thinktandem.io/sales/customer-profiles.html
* Sales calls (scripts)
  * NEW_DOCS_LOCATION
  * https://docs.v1.thinktandem.io/sales/sales-script.html
* Writing RFPs
  * NEW_DOCS_LOCATION
  * https://docs.v1.thinktandem.io/sales/rfp-process.html
* Doing potential hire interviews
  * NEW_DOCS_LOCATION
* Sending invoices
  * https://docs.v1.thinktandem.io/managing/invoicing.html
  * NEW_DOCS_LOCATION
* conducting quarterly reviews

**Comment by pirog** [comment]
@serundeputy ok, this is pretty good. here is how i recommend you proceed based on this feedback. Spin up a whole bunch more tasks that we can then assign to relevant people. I would then self assign one or more to yourself based on what you think you can accomplish this/next week. 

- [ ] Spin up a task to port over all the "ready to go docs",  eg ones that do not require more than trivial editing, as part of this it might be good to start by figuring out where each should live eg Handbook -> Sales, Guides -> Interviewing
  * https://docs.v1.thinktandem.io/hiring/reference-check.html (make any minor edits you think are needed)
  * https://docs.v1.thinktandem.io/managing/invoicing.html
  * https://docs.v1.thinktandem.io/managing/quarterly-review.html
  * I'm going to drop your feedback for sales over in #45 for @reynoldsalec and @labboy0276 
  * I'd also create a "next task" here for someone, probably @reynoldsalec/@pirog, to review once moved over
 - [ ] Create a task to flesh out "our interview process"
-  [ ] Create a new task for https://docs.v1.thinktandem.io/discovery/accessibility-checklist.html, im guessing this, and other project checklists might be better as GitHub issues htat we can automatically populate into a repo. I suspect it will be rare for someone to come back to the docs to find this kind of stuff.

**Comment by serundeputy** [comment]
>  Spin up a task to port over all the "ready to go docs", eg ones that do not require more than trivial editing, as part of this it might be good to start by figuring out where each should live eg Handbook -> Sales, Guides -> Interviewing
https://docs.v1.thinktandem.io/hiring/reference-check.html (make any minor edits you think are needed)
https://docs.v1.thinktandem.io/managing/invoicing.html
https://docs.v1.thinktandem.io/managing/quarterly-review.html

* https://github.com/thinktandem/tandem/issues/60

> Create a task to flesh out "our interview process"

* https://github.com/thinktandem/tandem/issues/69

> Create a new task for https://docs.v1.thinktandem.io/discovery/accessibility-checklist.html, im guessing this, and other project checklists might be better as GitHub issues htat we can automatically populate into a repo. I suspect it will be rare for someone to come back to the docs to find this kind of stuff.

*
