### ISSUE TITLE
Design a Campaign for a Service Product

### ISSUE THREAD

**Issue by reynoldsalec** [thinktandem/tandem#41]
## What is to be done?

Design a campaign for the highest ranked service product designated from the discussion in #40. At the end of this issue we should be ready to create and execute the campaign.

- [ ] Who is the audience for the campaign?
- [ ] What is the best channel(s) to use to reach them?
- [ ] What type of content will we need to create (emails/landing page/etc.)
- [ ] Talking points necessary for sales convos?
- [ ] Price points to try out.

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task

## Next steps(s)

- Create Sales Campaign (#42)

**Comment by pirog** [comment]
It's not the sexiest campaign but we are currently starting to make moves on a Tandem security policy that should allow us to know about updates and apply them pretty quickly. 

This might be an interesting service for people who have been burned by security update negligence in the past and could be a good "foot in the door" to additional services.

Downsides here are clients who have been negligent either through incompetence or ignorance about security updates might 1.) be bad to work with 2.) not have a ton of resources to spend on their tech.
