### ISSUE TITLE
Create Service Product Campaign

### ISSUE THREAD

**Issue by reynoldsalec** [thinktandem/tandem#42]
## What is to be done?

Using the campaign outline produced in #41, create the content necessary to launch the campaign. Note that this task should be broken into multiple tasks (ex: "build a landing page. Write a drip email campaign.)

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task

## Next steps(s)

- [ ] Execute the Service Product Campaign (#43)
