### ISSUE TITLE
Execute Service Product Campaign

### ISSUE THREAD

**Issue by reynoldsalec** [thinktandem/tandem#43]
## What is to be done?

Kickoff the service product campaign created in #42 and hand-off to whoever the responsible sales person will be.

This will probably be a more minor task, but all of this depends on the design of the campaign.

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task

## Next steps(s)

- [ ] Document Service Product Process (#44)
