### ISSUE TITLE
Add new tandem docs site to track in google analytics

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#47]
## What is to be done?

We need to get our new docs site https://docs.thinktandem.io/ to track in Google Analytics. It looks like this is pretty straightforward to do in vuepress, see: https://vuepress.vuejs.org/config/#ga

You may need to ping @pirog @reynoldsalec or @labboy0276 for a GA ID

Let's get this dialed up and verify it works!

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task

## Next Tasks

- [ ] #52
