### ISSUE TITLE
Roadmap and/or plan for our mannequin usage? 

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#51]
## Prompt

We've been using mannequin recently as the styleguide for our projects and it seems like a legit solution thats been better than things we've tried in the past. However, we do not have a clear sense of how it fits into Tandem long term, who the "owner" of it is on our end, how it fits into our sales process, devops, start states, etc.

Also note that we are good friends with Last Call Media so it would be fairly easy to each out and get a run down from them on their plans and roadmap for the future. im guessing that intel should be considered a prerequisite.  

This is definitely more of an open ended question but i'd be interested to hear some ideas on how we integrate mannequin into our flow so that a few years from now it doesn't end up being a bunch of technical debt that nobody understands. It might be worth thinking about this from a broader "tools" perspective eg how do we make sure the tools, projects, etc we invest in end stand the test of time as best they can. 

## Ticket Checklist

Make sure you complete the following checklist

- [x] I'm aware of [what a discussion actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've assigned this task to myself and one of the Keepers of the Faith
- [x] I've **not** set a story point estimation
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc

## Ping some folks!

Just wanted to get this queued up for now, guessing we wont get to it for awhile but once it makes more sense the peoples will be pinged

## Follow up tasks

Nothing yet!
