### ISSUE TITLE
Let's start to get a handle on our start states

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#54]
## What is to be done?

We do various kinds of projects at Tandem. Some of these projects can be created from "seeds" or start states that live in the Tandem GitHub org. Some were created from open source seed projects. 

However, it's not exactly clear what repos are seeds, which ones should be used for what kind of projects, what upstream a given project has, etc. SO, we need to get a better handle on:

1. What kinds of projects does Tandem currently do?
2. Which of these projects have, or need, a seed or start state?
3. What are our guidelines around creating, maintaining and/or suggesting a new start state? The most important thing there is how do we minimize maintenance on our end eg we should probably be forking a well known and supported open source project as an upstream.
4. Where do start states sit in our project creation process?
5. What kinds of things should live in a start state, what kind of things should live in the Tandem repo?
6. What should our new project creation or update project from start state workflow be?
7. How do we keep track of all our start states, the projects that use them, who is responsible for the start state, etc?

Let's start by answering some of these basic questions, generating some follow up tasks, documenting some shit and then we can start to actually build out our "start state delivery system". 

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

Going to want to make new cards for the below eventually but i'm guessing we will want _at least_ these. @TODO: let's make sure to add more based on the results of this ticket

- [x] Make a spreadsheet of our current projects, their upstreams, architect, type of project, etc
- [x] Make a spreadsheet of our current start states, their upstreams, current maintainers, type of projects they are made for, etc. Let's also identify any kinds of projects that we need a start state for but do not currently have one
- [ ] Let's document guidelines around creating start states that answer the 3/4/5/6 questions in the issue description

**Comment by pirog** [comment]
@labboy0276, @mikemilano discovered this interesting feature, might be worth exploring it to see how it works at some point
https://help.github.com/en/articles/creating-a-template-repository

**Comment by labboy0276** [comment]
Here is the spreadsheet: https://docs.google.com/spreadsheets/d/12zfVOBGhCA3dX9Wm5_e0fCbUTPO1_XRnAKNmepQLi2s/edit?usp=sharing

**Comment by labboy0276** [comment]
1. What kinds of projects does Tandem currently do?

Currently Tandem primarily engages in small to mid sized Drupal 7/8 based projects.  Within that space Tandem can handle any aspects from Design to Development Site Builds, Migrations, to Support.   

We have also dabbled in Styleguiding with Mannequin, VueJS partial and fully decoupled sites, VuePress, and Laravel.  These are not out primary focus currently.  

2. Which of these projects have, or need, a seed or start state?

Currently we already have 2 start states to handle our biggest needs: Design to Development Site Builds in Drupal 8.  Those start states are https://github.com/thinktandem/template-drupal8 && https://github.com/thinktandem/template-minimis

3. What are our guidelines around creating, maintaining and/or suggesting a new start state? The most important thing there is how do we minimize maintenance on our end eg we should probably be forking a well known and supported open source project as an upstream.
4. Where do start states sit in our project creation process?
5. What kinds of things should live in a start state, what kind of things should live in the Tandem repo?
6. What should our new project creation or update project from start state workflow be?
7. How do we keep track of all our start states, the projects that use them, who is responsible for the start state, etc?

**Comment by pirog** [comment]
@labboy0276 alright ive spun up #78 based on what we did here
