### ISSUE TITLE
Broadly sketch out our project management cycle from "start work" to "deliver" 

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#59]
## What is to be done?

I went through our old docs looking for any PM stuff that might be worth keeping and there just isnt a lot there. So instead of auditing that material and figuring out whether we can still use/repurpose it to kick start documenting PM stuff let's just get right to it. 

So to start, let's just document in the broadest terms possible the various "phases" a project goes through from project start (eg when "work" has begun) to project delivery. I recognize this is not the entire lifecycle but we can try to wire this part of things up with sales as soon as we can. 

@dustinleblanc i think this would include a lot of stuff we've talked about in the past eg the things it takes to get to an MVP, then various client interaction cycles thereafter, and the various "pre launch checks" we'd like to do, and then finally launch and any assumed post launch things.

Another way to attack this would be answering the question: "generally, what order should we do various things" to maximize our success. Obviously things dont need to be strictly sequential but im guessing we will always want to try to attack a clients three most important deliverables before their nices-to-haves, as an example./

I'm not sure where this should live in our new docs (i guess in some sort of new PM section of the guides?) so im open to suggestions there.

## Task checklist

- [ ] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [ ] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [ ] I've added a story point estimation. **This should never exceed 3!!!**
- [ ] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [ ] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

TBH here but im guessing after we have a doc about this we will want to focus on a particular phase and start filling in the detail

**Comment by reynoldsalec** [comment]
I don't think this made it into our first docs, but some of the specific touchpoints mentioned in [this doc](https://docs.google.com/document/d/1Cu8M2kppQOP27BaHOXJ6pvNRQiKtbfmZpRWYGfeR1Vk/edit#heading=h.88sa3jfwgvx4) might be good food for thought, particularly as we make this more specific.

**Comment by reynoldsalec** [comment]
These seem to do a good job of documenting broadly where we are (mixed with some aspirational reaches towards greater "agility").

Generally I thought a couple of examples of activities undertaken in each stage would be good, and we may even be missing one or two steps; above referenced doc might be a good place to source those.

**Comment by pirog** [comment]
Merged this in and will spin up a more narrowly focused task based on our discussion on Monday
