### ISSUE TITLE
Port ready to go guides to new docs/vuepress.

### ISSUE THREAD

**Issue by serundeputy** [thinktandem/tandem#60]
## What is to be done?

In #35 we did an audit of the extant `Guides` from the eld docs site.  These are the ones that are deemed `ready to go` with minor to no edits.

Add each of these to the new docs site.

 Spin up a task to port over all the "ready to go docs", eg ones that do not require more than trivial editing, as part of this it might be good to start by figuring out where each should live eg Handbook -> Sales, Guides -> Interviewing
- [x] https://docs.v1.thinktandem.io/hiring/reference-check.html (make any minor edits you think are needed)
  * Location: Guides | Hiring

- [x] https://docs.v1.thinktandem.io/managing/invoicing.html
  * Location: Guides | Sales | Invoicing

- [x] https://docs.v1.thinktandem.io/managing/quarterly-review.html
  * Location: Guides | Business | Quarterly Reviews

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

- [ ] QA docs PR
- [ ] Merge docs PR pending QA approval

**Comment by serundeputy** [comment]
PR: https://github.com/thinktandem/tandem/pull/62
QA: https://pr-62-yozr5ny-txmhst4apts56.us-2.platformsh.site/guides/
