### ISSUE TITLE
Spin up a Lando-Tandem repo to house the `tandem` lando plugin.

### ISSUE THREAD

**Issue by serundeputy** [thinktandem/tandem#76]
## What is to be done?

Start a repo to facilitate team collaboration on the `tandem` Lando plugin to help us automate our agency needs.

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [ ] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [ ] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

Paste in a link to any tasks or discussions that should be done after this one is merged. You should _always_ try to find a "next thing" (or more) that can be done to continue the chain of progress.

- [ ] GET FOLLOW UP ISSUES

**Comment by serundeputy** [comment]
The repo has been spun: https://github.com/thinktandem/lando-tandem
and we have https://github.com/thinktandem/tandem/issues/78 which will fuel the spec for automating the things once we nail down the things in #78 

@pirog I'm going to close this ... reopen if needed.

**Comment by pirog** [comment]
Sounds good @serundeputy! in the meantime do we have a task for the plugin delivery mechanism eg the bash script you are working on? That seems like something you can keep working on until @labboy0276 is done with #78

**Comment by serundeputy** [comment]
@pirog The bash script is here: https://github.com/thinktandem/lando-tandem/blob/master/getPlugin.sh
the same repo that has the test `lando welcome` command.

**Comment by serundeputy** [comment]
oh; a task, no; i'll spin one up!

**Comment by pirog** [comment]
yes! a task. even if its "already done" we need to track that shit!

at the very least we need to define a rough spec about what the fuck this thing is gonna do.

**Comment by serundeputy** [comment]
yes; and it needs more abstraction.  I'll spin up the task and we can flesh it out over there.
