### ISSUE TITLE
Review and bring some old HRish docs up to date

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#77]
## What is to be done?

in #60 and #62 @serundeputy moved over some docs from the old site that were "more or less right"
* https://docs.thinktandem.io/guides/invoicing.html
* https://docs.thinktandem.io/guides/quarterly-review.html
* https://tandem-docs.lndo.site/guides/reference-check.html

We should review these docs to make sure they still reflect the facts on the ground. If they dont they should be brought up to date, removed or reorganized as needed. We should also ask whether they can be improved. For example the "hiring" section seems incomplete, see #69. 

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [ ] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [ ] I've added a story point estimation. **This should never exceed 3!!!**
- [ ] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [ ] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

@reynoldsalec or @labboy0276 to spin up new issues if there are subsequent tasks we should add to improve from here. 

Also 
- [ ] #69

**Comment by labboy0276** [comment]
@reynoldsalec @pirog after reviewing these docs, The one I have the most exp with is the invoicing one and I made a slight change here: https://github.com/thinktandem/tandem/pull/96

The other 2 I think @reynoldsalec would be more apt to win if there are changes since it all looks ok to me from my exp with them.

**Comment by pirog** [comment]
@labboy0276 im going to close this out but can you spin up a new task for the two things that @reynoldsalec needs to win. i will follow up about this in our next 1-on-1?

**Comment by labboy0276** [comment]
@pirog https://github.com/thinktandem/tandem/issues/111 was created as a follow up
