### ISSUE TITLE
Create a discussion around what would be the highest impact and fastest improvement to our project lifecycle

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#80]
## What is to be done?

We are going to dive deep into our process on this one eg here is our first `task to make a discussion`. I've done this because i'd like for us to submit discussions that are limited in scope, can be resolved via async communication and can spawn reasonable tasks to improve our situation. Hopefully the guidelines i've provided below help do that. If they do not i would appreciate your feedback so i can do better next time!

Anyway, onto the actual task at hand:

We've got a doc that currently reflects (more or less) our project lifecycle 
https://docs.thinktandem.io/guides/project-lifecycle.html#full-project-contract-signing

We've also go some more inspirational things over at
https://github.com/thinktandem/tandem/compare/59/project-lifecycle

@reynoldsalec @dustinleblanc let's identify the next, best thing we can do to improve the project lifecycle and create a discussion around it. 

As you do so make sure you are thinking from our value of focusing on important shit and finding easy to change things that have high impact. To do that it might help to:

* Think about actual real problems we currently have as opposed to changes we could make to fend off hypothetical future problems
* Think about which of these problems has a clear improvement pathway
* Think about which of these problems is the biggest roadblock to us achieving our mission
* Think about a small, single thing (eg under 3 story points) we can do to improve this problem

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

- [ ] Create a discussion based on what you think is the next best thing we can do to imrpove our project lifecycle things

**Comment by dustinleblanc** [comment]
@reynoldsalec The number one item on my list is bringing in some principles of [concurrent design and manufacturing](https://en.wikipedia.org/wiki/Concurrent_design_and_manufacturing).

Figuring this out *feels* like the largest opportunity for us to improve on key project performance metrics such as velocity, delta to budget, and delta to deadline.

**Comment by dustinleblanc** [comment]
Created #124.

**Comment by pirog** [comment]
awesome, going to close this out for now
