### ISSUE TITLE
Create a plugin delivery mechanism eg a bash script.

### ISSUE THREAD

**Issue by serundeputy** [thinktandem/tandem#85]
## What is to be done?

Context of the Problem
-------------------------------

Tandem intends to be able to deliver contrib plugins to Lando users. In the long term we'll need public infrastructure for this ecosystem. In the short term Tandem will dogfood this mechanism with a smaillish roll out of some automation of some tasks that we know we always have to repeat across projects, e.g. spin up devs on existing projects, create new projects, integrate our projects with other services like github, p.sh, travis, etc.

Scope of this Card: Plugin Delivery Mechanism
---------------------------------------------------------------

With that context in mind the first step is a mechanism to deliver plugins to Lando users.
The initial PoC is a bash script that can provide a simple way to Lando users to specify a name of a plugin and have it downloaded to there machine in a place that Lando recognnizes and will then expose the features (commands) of that plugin to the Lando user in question.

* PoC is here https://github.com/thinktandem/lando-tandem
  * the state of this current implementation is that it will download a plugin that provides a `lando welcome` command:

![image](https://user-images.githubusercontent.com/6763671/62214860-e076be00-b373-11e9-9bc0-3dac15565008.png)

this bash script lives here: https://github.com/thinktandem/lando-tandem/blob/master/getPlugin.sh

TODO: Proposed Architecture
---------

* We need a new GitHub org and we need to decide what to call it; and then it can be the official place for lando plugins
  * Possible org names:
    * `lando-contrib`
    * `lando-plugins`
    * other ideas _________________
* Once we have this new org we can abstract the script to look there for a provided machine name of a plugin, i.e.

```bash
curl -Ls <onTheInternetURLTo/getPlugin.js> --name <PLUGIN_MACHINE_NAME>
```

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [ ] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [ ] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

Once we have the plugin delivery script follow ups are likely to be to create cards for new plugins Tandem wishes to develop.

- [ ] TODO: Spin up card for `tandem` lando plugin
  - A likely first feature for the `tandem` plugin is `lando create-project` command to spin up a new github repo from a start state, populate the backlog of said repo with known issues we need in all projects, and integrate p.sh workflows, travis, etc.

**Comment by pirog** [comment]
@serundeputy just to _clearly_ scope this a bit better. We are not trying to create a mechanism to delivery ANY plugin. We are writing a script that Tandem devs can use to get the Tandem plugin.

Eventually we might abstract, generalize, etc as part of a broader `lando plugin install` thing but lets not overcomplicate for now!

**Comment by serundeputy** [comment]
Great; so essentially we are done here and can move onto #86 which could probably use some help with scope as well.

Unless we want to get that packaging/release thing happening that happens in `hyperdrive` and allows the script to be easily run from the internet.

**Comment by pirog** [comment]
@serundeputy so before we get ahead of ourselves i think we probably want to take a step back and ask some important but less exciting questions around the management, devops, etc of this repo. Probably best to do that next time we meet!
