### ISSUE TITLE
Populate the backlog for new projects.

### ISSUE THREAD

**Issue by serundeputy** [thinktandem/tandem#86]
## What is to be done?

Add to our docs in #78 to include populating an initial backlog.

Current cards we've identified:

* Migrations
  * Preferably with some way to QA them in parts or in whole
* SEO
  * Google Analytics
  * GA in specific and in general identifying the scope of SEO for the project (how important is it to the project, i.e. RMC is not very to Poets.org which is very very)
.
.
.

If others can think of cards we need across all projects we can either add them here or in follow up issues.

Automate this with our `lando-tandem` plugin i.e. add a command to that plugin that communicates with the GitHub API to write out those cards to the project that is being spun up.

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [ ] I've added a story point estimation. **This should never exceed 3!!!**
- [ ] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [ ] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

* TODO: spin up follow up cards if necessary.

**Comment by serundeputy** [comment]
Went the `sources` route discussed in @pirog and I's one on one.  Allowing the `lando-tandem` plugin to extend `lando init` command.

The current (code)[https://github.com/thinktandem/lando-tandem/blob/master/sources/createProject.js] offers a `tandem-create-project` option when `init`ing and app:

![image](https://user-images.githubusercontent.com/6763671/62369579-0e880980-b4fe-11e9-9d35-26bb4836c11e.png)


Having trouble after the selection of that option to show list of tandem start states: https://github.com/thinktandem/lando-tandem/blob/master/sources/createProject.js#L16

That is what I have so far.

**Comment by pirog** [comment]
@serundeputy its not clear to me how the above comment advances this ticket. Perhaps you commented in the wrong place?

Regardless and as a rule let's definitely not work on tickets that are still in "new issues" until they've been triaged, scoped, clarified and prioritized into a swimlane.

Let's use our meeting next week to plan out the next 4-5 tasks we want to do re: the `lando-tandem` plugin

**Comment by pirog** [comment]
So, in an effort to scope this better its not exactly clear what the goal/deliverable of this card is to me. Are we wiring up the plugin to push out new tickets to projects? Are we just defining/listing those tickets? Are we doing both? 

I'm guessing we would benefit from a separate ticket that is a group discussion about the kinds of tickets (and maybe common github labels too?) we would want in all our projects. And then a ticket whose purposes is to just a PoC for a `lando init` that can push up an issue/label to github. 

That said, it _feels_ to me like we still have some things we'd want to tackle first: we still dont really have a feature set for this plugin and i'm guessing there is more to be done around the management of this plugin eg its usage is not documented anywhere and making sure people always have the latest version is going to be super critical especially early on. I'd take some time over the weekend to think about the order of operations and content for all of these concerns and then we can spin up some tickets in our next meeting!

**Comment by pirog** [comment]
closing this out in favor of forthcoming tix from @serundeputy
