### ISSUE TITLE
Improve onboarding and wrap up docs

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#87]
## What is to be done?

I've done a first pass on porting, reorganizing and consolidating our old onboarding-ish docs into a new "handbook"
https://tandem-docs.lndo.site/handbook/

However, i am guessing there are some things that may no longer be relevant and some things that may be missing. 

@serundeputy i'd like you to focus in particular on 
https://tandem-docs.lndo.site/handbook/onboarding.html
https://tandem-docs.lndo.site/handbook/wrap.html

In particular, pretend you are a new developer being onboarded and ask "does this onboarding checklist and wrap up taskz" get me in a position to hit the ground running eg is there anything you use in you day-to-day as a developer that is grossly omitted from here? Feel free to make other suggestions for improvement as well. Do not drop the suggestions here. Just spin up a PR right away and we can do the review that way. Also do not worry abut catching everything because @reynoldsalec will also be doing a pass when you are done.

@reynoldsalec i'd like for you to review said PR when it's up with an eye for the same things.

## Task checklist

- [ ] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [ ] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [ ] I've added a story point estimation. **This should never exceed 3!!!**
- [ ] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [ ] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

Paste in a link to any tasks or discussions that should be done after this one is merged. You should _always_ try to find a "next thing" (or more) that can be done to continue the chain of progress.

> Example:
> - [ ] Description of a next ticket #link-to-that-ticket
> - [ ] Description of another ticket if applicable #link-to-that-ticket
> - [ ] Description of another ticket if applicable #link-to-that-ticket
> - [ ] ...
> - [ ] Description of Nth ticket if applicable #link-to-that-ticket
