### ISSUE TITLE
Improve HR-y handbook docs

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#88]
## What is to be done?

Being mindful that @serundeputy is working on #87 it would be good to go through Handbook docs and make sure they reflect facts on the ground. 

@reynoldsalec this is all you!

## Task checklist

- [ ] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [ ] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [ ] I've added a story point estimation. **This should never exceed 3!!!**
- [ ] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [ ] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)
