### ISSUE TITLE
Create a discussion around what would be the highest impact and fastest improvement to our dev flow

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#90]
## What is to be done?

Similarly to #80 we are going to dive metadeep into our process on this one and make a task to make a discussion. I've done this because i'd like for us to submit discussions that are limited in scope, can be resolved via async communication and can spawn reasonable tasks to improve our situation. Hopefully the guidelines i've provided below help do that. If they do not i would appreciate your feedback so i can do better next time because this is mostly on me!

So i'll try to keep this pretty simple. We have our current code contribution workflow for _most_ of our projects over here
https://docs.thinktandem.io/guides/contributing-code.html

It is a good starting point for _most_ of our platform.sh projects but there may be a bunch of cases it doesnt cover well, either because its not flexible enough (which i think it is by the way :)) or because those cases are not documented well. We've had a great discussion over here about the obvious pros/cons
https://github.com/thinktandem/tandem/issues/72

@mikemilano your mission is to identify _a single_ and pressing current or going-to-be-current-soon problem with our current code contribution process and then suggest a path of not a ton of resistance solution to address the problem by submitting a discussion. It doesn't need to FIX everything but ideally it should result in a tangible improvement to our process without a ton of effort. I think a key part to success here is to digest the responses over at https://github.com/thinktandem/tandem/issues/72
and then use your best judgement about how to advance things!

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

- [ ] Create a discussion!

**Comment by pirog** [comment]
@mikemilano im going to close this out for now. its a little too meta and i think the work you and @serundeputy are doing on the Tandem plugin/hub is going to provide a good base to continually improve dev flow anyway. 

also we've got enough stuff to work on ;)
