### ISSUE TITLE
[lando-tandem plugin] We need TravisCI standards and sanity checks.

### ISSUE THREAD

**Issue by serundeputy** [thinktandem/tandem#97]
## What is to be done?

Need to spin up the DevOps for a `.travis.yml` config to run
* code standards checks
* sanity checks
  * pull in the `lando-tandem` plugin and run the `lando welcome` command and check for exit 0.

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

This is best practice and will ensure our #93 MVP is on the free and easy path.

**Comment by serundeputy** [comment]
- [x] Dialed in `eslint` w/ `.eslint.json` from `lando/lando`, add `yarn test` to `package.json` to run linter
- [x] Added `.travis.yml` to install `lando/hyperdrive`, run `yarn test`, and `lando welcome` in CI

https://github.com/thinktandem/lando-tandem

@pirog I think it is ok to close this unless you have input or follow up issues.

**Comment by pirog** [comment]
nice @serundeputy this looks good to me!
